const canvas = document.querySelector('#board');
const ctx = canvas.getContext('2d');
const nameInput = document.querySelector('#name');
const colsInput = document.querySelector('#cols');
const rowsInput = document.querySelector('#rows');
const difficulty = document.querySelector('#difficulty');
const start = document.querySelector('#start');
const message = document.querySelector('#message');
const turn = document.querySelector('#turn');
const playerScore = document.querySelector('#player-score b');
const botScore = document.querySelector('#bot-score b');
const soundButton = document.querySelector('#sound');
let sound = true, audio, game, hover = null;

const localKey = 'dox-n-bots-scores';
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const id = (a, b) => a < b ? `${a}:${b}` : `${b}:${a}`;
function tone(frequency, duration=.035, type='sine') { if (!sound) return; audio ??= new AudioContext(); const o=audio.createOscillator(), g=audio.createGain(); o.type=type;o.frequency.value=frequency;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration); }
function createGame() { const cols=clamp(Number(colsInput.value)||5,2,10), rows=clamp(Number(rowsInput.value)||5,2,10); return {cols,rows,edges:new Set(),boxes:new Map(),player:0,bot:0,playerTurn:true,finished:false}; }
function geometry(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const pad=Math.max(28,Math.min(r.width,r.height)*.09),sx=(r.width-pad*2)/(game.cols-1),sy=(r.height-pad*2)/(game.rows-1);return{w:r.width,h:r.height,pad,sx,sy}}
function dot(index){return{x:index%game.cols,y:Math.floor(index/game.cols)}}
function point(index,g){const d=dot(index);return{x:g.pad+d.x*g.sx,y:g.pad+d.y*g.sy}}
function edges(){const out=[];for(let y=0;y<game.rows;y++)for(let x=0;x<game.cols;x++){let a=y*game.cols+x;if(x<game.cols-1)out.push([a,a+1]);if(y<game.rows-1)out.push([a,a+game.cols])}return out}
function boxEdges(x,y){const a=y*game.cols+x;return[id(a,a+1),id(a,a+game.cols),id(a+1,a+game.cols+1),id(a+game.cols,a+game.cols+1)]}
function completed(edge){const [a,b]=edge, da=dot(a),db=dot(b), candidates=[];if(da.y===db.y){for(const y of [da.y-1,da.y])if(y>=0&&y<game.rows-1)candidates.push([Math.min(da.x,db.x),y])}else{for(const x of [da.x-1,da.x])if(x>=0&&x<game.cols-1)candidates.push([x,Math.min(da.y,db.y)])}return candidates.filter(([x,y])=>{const key=`${x}:${y}`;return !game.boxes.has(key)&&boxEdges(x,y).every(e=>game.edges.has(e))})}
function draw(){if(!game)return;const g=geometry();ctx.clearRect(0,0,g.w,g.h);for(const [key,owner] of game.boxes){const[x,y]=key.split(':').map(Number);ctx.fillStyle=owner==='player'?'#f4512940':'#1d211e18';ctx.fillRect(g.pad+x*g.sx+4,g.pad+y*g.sy+4,g.sx-8,g.sy-8)}const drawEdge=(edge,color,width=4)=>{const[a,b]=edge,p=point(a,g),q=point(b,g);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()};for(const edge of edges())if(game.edges.has(id(...edge)))drawEdge(edge,'#1d211e',5);if(hover&&!game.edges.has(id(...hover)))drawEdge(hover,'#6e736a',4);for(let i=0;i<game.cols*game.rows;i++){const p=point(i,g);ctx.fillStyle='#1d211e';ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()}playerScore.textContent=game.player;botScore.textContent=game.bot;turn.textContent=game.finished?'GAME OVER':game.playerTurn?'YOUR TURN':'BOT THINKING';}
function chooseHover(event){if(!game||game.finished||!game.playerTurn)return null;const r=canvas.getBoundingClientRect(),g=geometry(),x=event.clientX-r.left,y=event.clientY-r.top;let closest=null,best=Infinity;for(const edge of edges()){if(game.edges.has(id(...edge)))continue;const[a,b]=edge,p=point(a,g),q=point(b,g),vx=q.x-p.x,vy=q.y-p.y,t=clamp(((x-p.x)*vx+(y-p.y)*vy)/(vx*vx+vy*vy),0,1),dx=x-(p.x+t*vx),dy=y-(p.y+t*vy),dist=Math.hypot(dx,dy);if(dist<best){best=dist;closest=edge}}return best<Math.max(28,Math.min(g.sx,g.sy)*.38)?closest:null}
function take(edge, owner){game.edges.add(id(...edge));const won=completed(edge);for(const[x,y]of won)game.boxes.set(`${x}:${y}`,owner);if(owner==='player')game.player+=won.length;else game.bot+=won.length;tone(won.length?330:170,won.length?.11:.035,won.length?'triangle':'sine');if(!won.length)game.playerTurn=!game.playerTurn;const total=(game.cols-1)*(game.rows-1);if(game.boxes.size===total){game.finished=true;const result=game.player===game.bot?'DRAW':game.player>game.bot?'YOU WIN':'BOT WINS';message.textContent=`${result}. ${game.player} boxes for ${nameInput.value.trim()}.`;saveScore();}draw();if(!game.playerTurn&&!game.finished)setTimeout(botMove,360);}
function risk(edge){const temporary=new Set(game.edges);temporary.add(id(...edge));let thirds=0;for(let y=0;y<game.rows-1;y++)for(let x=0;x<game.cols-1;x++){const count=boxEdges(x,y).filter(e=>temporary.has(e)).length;if(count===3)thirds++}return thirds}
function botMove(){if(!game||game.playerTurn||game.finished)return;const available=edges().filter(e=>!game.edges.has(id(...e)));const scoring=available.filter(e=>completed(e).length);let choice;if(difficulty.value==='noob')choice=available[Math.floor(Math.random()*available.length)];else if(scoring.length)choice=scoring.sort((a,b)=>completed(b).length-completed(a).length)[0];else if(difficulty.value==='god')choice=available.sort((a,b)=>risk(a)-risk(b))[0];else choice=available.sort((a,b)=>risk(a)-risk(b)+Math.random()*.7)[0];take(choice,'bot');}
async function saveScore(){const payload={name:nameInput.value.trim(),score:game.player,width:game.cols,height:game.rows};const local=JSON.parse(localStorage.getItem(localKey)||'[]');local.push(payload);localStorage.setItem(localKey,JSON.stringify(local));try{await fetch('/api/leaderboard',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});}catch{}loadScores();}
async function loadScores(){let scores;try{const r=await fetch('/api/leaderboard');if(!r.ok)throw Error();scores=await r.json();}catch{scores=JSON.parse(localStorage.getItem(localKey)||'[]').sort((a,b)=>b.score-a.score).slice(0,10)}const list=document.querySelector('#scores'),template=document.querySelector('#score-row');list.replaceChildren();(scores.length?scores:[{name:'BE THE FIRST',score:'—'}]).slice(0,10).forEach((entry,index)=>{const row=template.content.cloneNode(true);row.querySelector('.rank').textContent=`${String(index+1).padStart(2,'0')} /`;row.querySelector('.score-name').textContent=entry.name;row.querySelector('.score-points').textContent=entry.score==='—'?'—':`${entry.score} BOX${entry.score===1?'':'ES'}`;list.append(row)});}
start.addEventListener('click',()=>{const name=nameInput.value.trim();if(name.length<3||name.length>50){message.textContent='NAME NEEDS 3–50 CHARACTERS.';nameInput.focus();return}game=createGame();hover=null;message.textContent=`${name.toUpperCase()} VS ${difficulty.value.toUpperCase()} BOT.`;draw();});canvas.addEventListener('pointermove',event=>{const next=chooseHover(event);if(next&&(!hover||id(...next)!==id(...hover)))tone(480,.018);hover=next;draw()});canvas.addEventListener('pointerleave',()=>{hover=null;draw()});canvas.addEventListener('pointerdown',()=>{if(hover&&game?.playerTurn)take(hover,'player')});window.addEventListener('resize',draw);soundButton.addEventListener('click',()=>{sound=!sound;soundButton.textContent=`SOUND: ${sound?'ON':'OFF'}`;soundButton.setAttribute('aria-pressed',String(sound));});loadScores();
