ALTER TABLE scores ADD COLUMN opponent TEXT NOT NULL DEFAULT 'BOT';
ALTER TABLE scores ADD COLUMN winner TEXT NOT NULL DEFAULT 'BOT';
ALTER TABLE scores ADD COLUMN margin INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scores ADD COLUMN mode TEXT NOT NULL DEFAULT 'SOLO';
ALTER TABLE scores ADD COLUMN detail TEXT NOT NULL DEFAULT 'CASUAL';
